export enum ErrorCode {
  MISSING_FIELDS = "MISSING_FIELDS",
  INVALID_FORMAT_CPF = "INVALID_FORMAT_CPF",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  CPF_ALREADY_EXISTS = "CPF_ALREADY_EXISTS",
  SERVER_ERROR = "SERVER_ERROR",
}
