export enum ErrorCode {
  MISSING_FIELDS = "MISSING_FIELDS",
  INVALID_FORMAT_CPF = "INVALID_FORMAT_CPF",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  CPF_ALREADY_EXISTS = "CPF_ALREADY_EXISTS",
  SERVER_ERROR = "SERVER_ERROR",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND",
  INVALID_PAYMENT_METHOD = "INVALID_PAYMENT_METHOD",
  USER_ID_NOT_FOUND = "USER_ID_NOT_FOUND"
}
